
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.unbosque.interpreter.parser;

/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 19;
  public static final int HASTAQUE = 7;
  public static final int PLUS = 18;
  public static final int PCOMMA = 10;
  public static final int LEER = 8;
  public static final int ENTONCES = 3;
  public static final int VARIABLE = 13;
  public static final int MEQ = 24;
  public static final int LE = 21;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int SINO = 5;
  public static final int DIV = 20;
  public static final int MINUS = 17;
  public static final int SI = 2;
  public static final int ESCRIBIR = 9;
  public static final int error = 1;
  public static final int ME = 22;
  public static final int EQ = 16;
  public static final int LEQ = 23;
  public static final int RPAR = 12;
  public static final int EQEQ = 15;
  public static final int FIN = 4;
  public static final int LPAR = 11;
  public static final int REPITA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SI",
  "ENTONCES",
  "FIN",
  "SINO",
  "REPITA",
  "HASTAQUE",
  "LEER",
  "ESCRIBIR",
  "PCOMMA",
  "LPAR",
  "RPAR",
  "VARIABLE",
  "NUMBER",
  "EQEQ",
  "EQ",
  "MINUS",
  "PLUS",
  "TIMES",
  "DIV",
  "LE",
  "ME",
  "LEQ",
  "MEQ"
  };
}

